"""pg_baseline — the single squashed Postgres baseline (SPEC-002 Step 6).

Replaces the 40 SQLite-era revisions, which now live in `alembic/legacy_sqlite/` as
reference only and are never run (G6.3). That chain could not be replayed against
Postgres regardless: it dies on a native-enum literal in `e5f6a7b8c9d0`, whose own
docstring says *"SQLite stores enums as VARCHAR, so no ALTER needed"* — precisely the
assumption that fails here.

Creates 43 tables: identity (6) + the tenant tables + the SPEC-002 additions.
**`waitlist` is deliberately absent (G6.4)** — SPEC-001 D1/D3 give the landing app a
standalone one-table database owned by the separate `alembic_landing/` tree, and
`alembic/env.py` excludes it from autogenerate so future diffs stay clean.

**Two things here that autogenerate does not produce, and why each is hand-added:**

1. **The G4 drift-guard trigger.** `DRIFT_GUARD_FUNCTION` is *imported* rather than
   pasted, so the PL/pgSQL body has exactly one definition — a copy here would drift
   from the one `create_all` installs, and the test suite builds its schema with
   `create_all`, so the two must agree or the drift test proves nothing about this
   migration. The trigger list is likewise derived from `Base.metadata`.

   The tension that creates: a released migration should be frozen, but this one reads
   current metadata. That is acceptable *for a baseline* — it is the initial schema, and
   pre-release it should be regenerated whenever the models change. If metadata gains a
   table without this file being regenerated, the guard would try to create a trigger on
   a table this migration never creates and the upgrade fails loudly rather than
   silently diverging. `test_baseline_matches_metadata` catches it before that.

2. **`DROP TYPE` for the 22 enums in `downgrade()`.** `op.drop_table` does not drop the
   Postgres enum *type* it created, so without this an
   `upgrade → downgrade → upgrade` cycle fails on "type already exists". That cycle is
   the spec's own verify clause for this step, so the omission would have failed the gate.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the custom Money type as a fully-qualified
# `mihomes.type.money.Money()` but does not emit an import for it, so the generated
# file raises NameError on the first Money column without this.
import mihomes.type.money  # noqa: F401

from mihomes.models import Base
from mihomes.tenancy.drift_guard import (
    DRIFT_GUARD_FUNCTION,
    DROP_DRIFT_GUARD_FUNCTION,
    trigger_ddl_statements,
)

# revision identifiers, used by Alembic.
revision: str = '0001_pg_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum types created implicitly by the sa.Enum() columns below. Listed explicitly
# because downgrade() has to drop them by name; see the docstring.
ENUM_TYPES = [
    'alertseverity', 'alertstatus', 'assetcondition', 'assettype', 'bookcondition',
    'budgetperiod', 'consumablestatus', 'documenttype', 'eventstatus',
    'expensefrequency', 'insurancetype', 'issueseverity', 'issuestatus',
    'propertystatus', 'propertytype', 'ptostatus', 'recurrencefrequency', 'staffrole',
    'taskcategory', 'taskpriority', 'taskstatus', 'workorderstatus',
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), server_default='household', nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='free', nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_status', sa.String(length=30), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_slug'), 'accounts', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_table('ai_conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('session_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_response', sa.Text(), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_conv_account_session', 'ai_conversations', ['account_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_account_id'), 'ai_conversations', ['account_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_account_entity', 'audit_log', ['account_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_account_id'), 'audit_log', ['account_id'], unique=False)
    op.create_index('ix_audit_log_account_ts', 'audit_log', ['account_id', 'timestamp'], unique=False)
    op.create_table('configurations',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'key', name='pk_configurations')
    )
    op.create_index(op.f('ix_configurations_account_id'), 'configurations', ['account_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('WARRANTY', 'CONTRACT', 'INVOICE', 'MANUAL', 'INSURANCE', 'PERMIT', 'REGULATION', 'SOP', 'REPORT', 'PHOTO', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_documents_account_slug')
    )
    op.create_index(op.f('ix_documents_account_id'), 'documents', ['account_id'], unique=False)
    op.create_table('guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('dietary_preferences', sa.String(length=300), nullable=True),
    sa.Column('room_preference', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_guests_account_slug')
    )
    op.create_index(op.f('ix_guests_account_id'), 'guests', ['account_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invites_account_email', 'invites', ['account_id', 'email'], unique=False)
    op.create_index(op.f('ix_invites_account_id'), 'invites', ['account_id'], unique=False)
    op.create_index(op.f('ix_invites_token_hash'), 'invites', ['token_hash'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'user_id', name='uq_membership_account_user')
    )
    op.create_index(op.f('ix_memberships_account_id'), 'memberships', ['account_id'], unique=False)
    op.create_index('uq_membership_one_owner', 'memberships', ['account_id'], unique=True, postgresql_where=sa.text("role = 'owner' AND status = 'active'"))
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_note_entity', 'notes', ['account_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_notes_account_id'), 'notes', ['account_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('PRIMARY', 'VACATION', 'SEASONAL', 'INVESTMENT', 'RENTAL', 'ESTATE', 'OTHER', name='propertytype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CARETAKER_MODE', 'UNDER_RENOVATION', name='propertystatus'), nullable=False),
    sa.Column('climate_zone', sa.String(length=50), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('occupied', sa.Boolean(), nullable=False),
    sa.Column('occupied_since', sa.Date(), nullable=True),
    sa.Column('occupied_until', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_properties_account_slug')
    )
    op.create_index(op.f('ix_properties_account_id'), 'properties', ['account_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_account_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['current_account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_id_hash'), 'sessions', ['session_id_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('HOUSEKEEPER', 'GROUNDSKEEPER', 'PROPERTY_MANAGER', 'DRIVER', 'CHEF', 'SECURITY', 'PERSONAL_ASSISTANT', 'OTHER', 'RESIDENT', 'OWNER', 'FAMILY_MEMBER', 'ASSOCIATE', name='staffrole'), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=50), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_staff_account_slug')
    )
    op.create_index(op.f('ix_staff_account_id'), 'staff', ['account_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'name', name='uq_tags_account_name')
    )
    op.create_index(op.f('ix_tags_account_id'), 'tags', ['account_id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_templates_account_slug')
    )
    op.create_index(op.f('ix_templates_account_id'), 'templates', ['account_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('service_categories', sa.JSON(), nullable=True),
    sa.Column('service_areas', sa.JSON(), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_info', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_vendors_account_slug')
    )
    op.create_index(op.f('ix_vendors_account_id'), 'vendors', ['account_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('source_entity_type', sa.String(length=50), nullable=True),
    sa.Column('source_entity_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='alertseverity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'SEEN', 'ACKNOWLEDGED', 'RESOLVED', name='alertstatus'), nullable=False),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_account_id'), 'alerts', ['account_id'], unique=False)
    op.create_index('ix_alerts_account_property', 'alerts', ['account_id', 'property_id'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('period', sa.Enum('MONTHLY', 'QUARTERLY', 'ANNUAL', name='budgetperiod'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('amount', mihomes.type.money.Money(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'category', 'period', 'period_start', name='uq_budget_property_category_period')
    )
    op.create_index(op.f('ix_budgets_account_id'), 'budgets', ['account_id'], unique=False)
    op.create_index('ix_budgets_account_property', 'budgets', ['account_id', 'property_id'], unique=False)
    op.create_table('consumables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('quantity_in_stock', sa.Float(), nullable=True),
    sa.Column('quantity_to_order', sa.Float(), nullable=True),
    sa.Column('par_level', sa.Float(), nullable=True),
    sa.Column('low_stock_threshold', sa.Float(), nullable=True),
    sa.Column('unit_price', mihomes.type.money.Money(), nullable=True),
    sa.Column('last_ordered_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'LOW', 'OUT', 'ORDERED', name='consumablestatus'), nullable=False),
    sa.Column('last_updated_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_consumables_account_slug')
    )
    op.create_index(op.f('ix_consumables_account_id'), 'consumables', ['account_id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('service_category', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('billing_frequency', sa.String(length=20), nullable=True),
    sa.Column('cost', mihomes.type.money.Money(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_account_id'), 'contracts', ['account_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expected_guests', sa.Integer(), nullable=True),
    sa.Column('budget', mihomes.type.money.Money(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_events_account_slug')
    )
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_table('insurance_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('carrier', sa.String(length=200), nullable=False),
    sa.Column('agent_contact', sa.String(length=200), nullable=True),
    sa.Column('insurance_type', sa.Enum('HOMEOWNERS', 'LIABILITY', 'UMBRELLA', 'VALUABLE_ARTICLES', 'VEHICLE', 'WORKERS_COMP', 'EVENT', 'OTHER', name='insurancetype'), nullable=False),
    sa.Column('coverage_limit', mihomes.type.money.Money(), nullable=True),
    sa.Column('deductible', mihomes.type.money.Money(), nullable=True),
    sa.Column('annual_premium', mihomes.type.money.Money(), nullable=True),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_policies_account_id'), 'insurance_policies', ['account_id'], unique=False)
    op.create_table('membership_property_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'property_id', name='uq_scope_membership_property')
    )
    op.create_index(op.f('ix_membership_property_scopes_account_id'), 'membership_property_scopes', ['account_id'], unique=False)
    op.create_table('recurring_expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', mihomes.type.money.Money(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('frequency', sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'CUSTOM_WEEKS', 'CUSTOM_MONTHS', name='expensefrequency'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('last_generated', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_expenses_account_id'), 'recurring_expenses', ['account_id'], unique=False)
    op.create_table('staff_properties',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('staff_id', 'property_id')
    )
    op.create_index(op.f('ix_staff_properties_account_id'), 'staff_properties', ['account_id'], unique=False)
    op.create_table('staff_pto_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('dates', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'DENIED', name='ptostatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('coverage_warning', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_pto_requests_account_id'), 'staff_pto_requests', ['account_id'], unique=False)
    op.create_table('tag_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_tag_assignment')
    )
    op.create_index('ix_tag_assign_account_entity', 'tag_assignments', ['account_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_tag_assignments_account_id'), 'tag_assignments', ['account_id'], unique=False)
    op.create_table('template_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('default_assignee_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_items_account_id'), 'template_items', ['account_id'], unique=False)
    op.create_table('vendor_properties',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'property_id')
    )
    op.create_index(op.f('ix_vendor_properties_account_id'), 'vendor_properties', ['account_id'], unique=False)
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_zones_account_slug')
    )
    op.create_index(op.f('ix_zones_account_id'), 'zones', ['account_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('recurring_expense_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('gcal_event_id', sa.String(length=200), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recurring_expense_id'], ['recurring_expenses.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_account_date', 'appointments', ['account_id', 'date'], unique=False)
    op.create_index(op.f('ix_appointments_account_id'), 'appointments', ['account_id'], unique=False)
    op.create_index('ix_appointments_account_recurring', 'appointments', ['account_id', 'recurring_expense_id'], unique=False)
    op.create_table('consumable_price_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consumable_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', mihomes.type.money.Money(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumable_price_entries_account_id'), 'consumable_price_entries', ['account_id'], unique=False)
    op.create_index('ix_consumable_prices_account_item', 'consumable_price_entries', ['account_id', 'consumable_id'], unique=False)
    op.create_table('event_guests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=False),
    sa.Column('rsvp_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'guest_id', name='uq_event_guest')
    )
    op.create_index(op.f('ix_event_guests_account_id'), 'event_guests', ['account_id'], unique=False)
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('space_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_spaces_account_slug')
    )
    op.create_index(op.f('ix_spaces_account_id'), 'spaces', ['account_id'], unique=False)
    op.create_index('ix_spaces_account_zone', 'spaces', ['account_id', 'zone_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('estimated_hours', sa.Float(), nullable=True),
    sa.Column('gcal_event_id', sa.String(length=200), nullable=True),
    sa.Column('zone_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('PLUMBING', 'HVAC', 'ELECTRICAL', 'FUEL_GAS', 'FIRE_SAFETY', 'SECURITY', 'HEALTH_ENV', 'EXTERIOR', 'LANDSCAPING', 'INTERIOR', 'APPLIANCES', 'OPERATIONS', 'STRATEGIC', 'GENERAL', name='taskcategory'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_tasks_account_slug')
    )
    op.create_index('ix_tasks_account_category', 'tasks', ['account_id', 'category'], unique=False)
    op.create_index('ix_tasks_account_due', 'tasks', ['account_id', 'due_date'], unique=False)
    op.create_index(op.f('ix_tasks_account_id'), 'tasks', ['account_id'], unique=False)
    op.create_index('ix_tasks_account_zone', 'tasks', ['account_id', 'zone_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('asset_type', sa.Enum('APPLIANCE', 'VEHICLE', 'VALUABLE', 'CONSUMABLE', 'EQUIPMENT', name='assettype'), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('make', sa.String(length=200), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('serial_number', sa.String(length=200), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', mihomes.type.money.Money(), nullable=True),
    sa.Column('warranty_expires', sa.Date(), nullable=True),
    sa.Column('condition', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='assetcondition'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('vehicle_info', sa.JSON(), nullable=True),
    sa.Column('valuable_info', sa.JSON(), nullable=True),
    sa.Column('equipment_info', sa.JSON(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('expected_lifespan_years', sa.Float(), nullable=True),
    sa.Column('replacement_cost_estimate', mihomes.type.money.Money(), nullable=True),
    sa.Column('last_serviced', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_assets_account_slug')
    )
    op.create_index(op.f('ix_assets_account_id'), 'assets', ['account_id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='bookcondition'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_books_account_slug')
    )
    op.create_index(op.f('ix_books_account_id'), 'books', ['account_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='issueseverity'), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'ASSESSED', 'SCHEDULED', 'IN_PROGRESS', 'RESOLVED', 'VERIFIED', name='issuestatus'), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('reported_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['reported_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_issues_account_slug')
    )
    op.create_index(op.f('ix_issues_account_id'), 'issues', ['account_id'], unique=False)
    op.create_index('ix_issues_account_reported_by', 'issues', ['account_id', 'reported_by_id'], unique=False)
    op.create_index('ix_issues_account_resolved_by', 'issues', ['account_id', 'resolved_by_id'], unique=False)
    op.create_table('task_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE', 'DAILY', 'WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'SEASONAL', 'ANNUAL', name='recurrencefrequency'), nullable=False),
    sa.Column('custom_cron', sa.String(length=100), nullable=True),
    sa.Column('season_spec', sa.String(length=100), nullable=True),
    sa.Column('next_due', sa.Date(), nullable=True),
    sa.Column('last_generated', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_index(op.f('ix_task_schedules_account_id'), 'task_schedules', ['account_id'], unique=False)
    op.create_table('asset_price_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', mihomes.type.money.Money(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_price_entries_account_id'), 'asset_price_entries', ['account_id'], unique=False)
    op.create_index('ix_asset_prices_account_asset', 'asset_price_entries', ['account_id', 'asset_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('vendor_name', sa.String(length=300), nullable=True),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('estimated_cost', mihomes.type.money.Money(), nullable=True),
    sa.Column('actual_cost', mihomes.type.money.Money(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ESTIMATED', 'APPROVED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('issue_id', sa.UUID(), nullable=True),
    sa.Column('completion_notes', sa.Text(), nullable=True),
    sa.Column('ai_report', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignee_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'slug', name='uq_work_orders_account_slug')
    )
    op.create_index(op.f('ix_work_orders_account_id'), 'work_orders', ['account_id'], unique=False)
    op.create_index('ix_work_orders_account_issue', 'work_orders', ['account_id', 'issue_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('amount', mihomes.type.money.Money(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('vendor_name', sa.String(length=300), nullable=True),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('appointment_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_account_appointment', 'transactions', ['account_id', 'appointment_id'], unique=False)
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_account_property', 'transactions', ['account_id', 'property_id'], unique=False)
    op.create_index('ix_transactions_account_vendor', 'transactions', ['account_id', 'vendor_id'], unique=False)
    op.create_index('ix_transactions_account_work_order', 'transactions', ['account_id', 'work_order_id'], unique=False)
    op.create_table('vendor_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('work_order_id', sa.UUID(), nullable=True),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('cost_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rated_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_ratings_account_id'), 'vendor_ratings', ['account_id'], unique=False)
    # ### end Alembic commands ###

    # G4 drift guard. Emitted after every table exists — a trigger cannot reference a
    # parent table that has not been created yet.
    #
    # Dialect-guarded exactly as `install_drift_guard()` guards the `create_all` path: the
    # guard is PL/pgSQL, and `CREATE OR REPLACE FUNCTION` is a syntax error on SQLite.
    # Applying the same rule in both places is the point — if the migration emitted it
    # unconditionally while `create_all` did not, the two schemas would differ by backend.
    #
    # **A SQLite database built from this migration therefore has no drift guard and no
    # RLS.** That is a property of running on SQLite, which SPEC-002 retires (RLS, the
    # non-owner app role, and transaction-local `set_config` all require Postgres). The
    # remaining SQLite callers are `init_db()`'s default URL and the CLI tests that use it;
    # **G13 owns re-pointing them.** Until then those tests exercise application logic
    # against a schema with no tenant enforcement — they are not evidence for A21.
    if op.get_bind().dialect.name == "postgresql":
        op.execute(DRIFT_GUARD_FUNCTION)
        for stmt in trigger_ddl_statements(Base.metadata):
            op.execute(stmt)


def downgrade() -> None:
    is_postgres = op.get_bind().dialect.name == "postgresql"

    # Drop the guard function first, with CASCADE, so its 52 triggers go with it.
    # Leaving it behind means the next upgrade's CREATE OR REPLACE silently inherits a
    # stale definition.
    if is_postgres:
        op.execute(DROP_DRIFT_GUARD_FUNCTION)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_ratings_account_id'), table_name='vendor_ratings')
    op.drop_table('vendor_ratings')
    op.drop_index('ix_transactions_account_work_order', table_name='transactions')
    op.drop_index('ix_transactions_account_vendor', table_name='transactions')
    op.drop_index('ix_transactions_account_property', table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_appointment', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_work_orders_account_issue', table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_account_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index('ix_asset_prices_account_asset', table_name='asset_price_entries')
    op.drop_index(op.f('ix_asset_price_entries_account_id'), table_name='asset_price_entries')
    op.drop_table('asset_price_entries')
    op.drop_index(op.f('ix_task_schedules_account_id'), table_name='task_schedules')
    op.drop_table('task_schedules')
    op.drop_index('ix_issues_account_resolved_by', table_name='issues')
    op.drop_index('ix_issues_account_reported_by', table_name='issues')
    op.drop_index(op.f('ix_issues_account_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_books_account_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_assets_account_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_tasks_account_zone', table_name='tasks')
    op.drop_index(op.f('ix_tasks_account_id'), table_name='tasks')
    op.drop_index('ix_tasks_account_due', table_name='tasks')
    op.drop_index('ix_tasks_account_category', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_spaces_account_zone', table_name='spaces')
    op.drop_index(op.f('ix_spaces_account_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_event_guests_account_id'), table_name='event_guests')
    op.drop_table('event_guests')
    op.drop_index('ix_consumable_prices_account_item', table_name='consumable_price_entries')
    op.drop_index(op.f('ix_consumable_price_entries_account_id'), table_name='consumable_price_entries')
    op.drop_table('consumable_price_entries')
    op.drop_index('ix_appointments_account_recurring', table_name='appointments')
    op.drop_index(op.f('ix_appointments_account_id'), table_name='appointments')
    op.drop_index('ix_appointments_account_date', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_zones_account_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_vendor_properties_account_id'), table_name='vendor_properties')
    op.drop_table('vendor_properties')
    op.drop_index(op.f('ix_template_items_account_id'), table_name='template_items')
    op.drop_table('template_items')
    op.drop_index(op.f('ix_tag_assignments_account_id'), table_name='tag_assignments')
    op.drop_index('ix_tag_assign_account_entity', table_name='tag_assignments')
    op.drop_table('tag_assignments')
    op.drop_index(op.f('ix_staff_pto_requests_account_id'), table_name='staff_pto_requests')
    op.drop_table('staff_pto_requests')
    op.drop_index(op.f('ix_staff_properties_account_id'), table_name='staff_properties')
    op.drop_table('staff_properties')
    op.drop_index(op.f('ix_recurring_expenses_account_id'), table_name='recurring_expenses')
    op.drop_table('recurring_expenses')
    op.drop_index(op.f('ix_membership_property_scopes_account_id'), table_name='membership_property_scopes')
    op.drop_table('membership_property_scopes')
    op.drop_index(op.f('ix_insurance_policies_account_id'), table_name='insurance_policies')
    op.drop_table('insurance_policies')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_contracts_account_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_consumables_account_id'), table_name='consumables')
    op.drop_table('consumables')
    op.drop_index('ix_budgets_account_property', table_name='budgets')
    op.drop_index(op.f('ix_budgets_account_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_alerts_account_property', table_name='alerts')
    op.drop_index(op.f('ix_alerts_account_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_vendors_account_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_templates_account_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_tags_account_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_staff_account_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_id_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_properties_account_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_notes_account_id'), table_name='notes')
    op.drop_index('ix_note_entity', table_name='notes')
    op.drop_table('notes')
    op.drop_index('uq_membership_one_owner', table_name='memberships', postgresql_where=sa.text("role = 'owner' AND status = 'active'"))
    op.drop_index(op.f('ix_memberships_account_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invites_token_hash'), table_name='invites')
    op.drop_index(op.f('ix_invites_account_id'), table_name='invites')
    op.drop_index('ix_invites_account_email', table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_guests_account_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_documents_account_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_configurations_account_id'), table_name='configurations')
    op.drop_table('configurations')
    op.drop_index('ix_audit_log_account_ts', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_account_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_account_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_ai_conversations_account_id'), table_name='ai_conversations')
    op.drop_index('ix_ai_conv_account_session', table_name='ai_conversations')
    op.drop_table('ai_conversations')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_accounts_slug'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###

    # op.drop_table leaves the enum TYPES behind, so a second upgrade would fail with
    # "type ... already exists". Dropping them is what makes the spec's
    # upgrade -> downgrade -> upgrade gate pass. SQLite has no enum types to drop.
    if is_postgres:
        for enum_name in ENUM_TYPES:
            op.execute(f'DROP TYPE IF EXISTS {enum_name}')
