"""document_access — per-person document grants (SPEC-004).

The owner (or an admin) chooses which staff member sees which document. This **replaces
`documents.staff_visible`** as the owner-controlled gate: that column gave one boolean per
document, so a ticked document was visible to *every* staff member in scope, and an estate has
paperwork appropriate for one person and not another.

`staff_visible` is **not dropped**. It never had a setter — no service argument, no route form
field, nothing in the UI, and the only writers in the tree were tests using raw SQL — so no data
depends on it, and `authz/query_scope.py` simply stops reading it. Dropping a column whose only
cost is being ignored, in a migration that would exist solely to remove it, trades a reversible
decision for an irreversible one.

Keyed on `staff`, not `memberships`, and that is the opposite call from `0007_telegram_links`. That
table's subject is a *capability*, so N6 requires the membership (a `StaffRole` contains its own
`OWNER`, and crossing the two would make a housekeeping "owner" an account owner). This table's
subject is the **people directory** the owner picks from, which is `staff`. The join to the
signed-in user runs through `staff.user_id` — the link `0008` added so that "which row is this
person" has a hard answer — which means a grant to a staff row with no login matches nothing, and
the picker offers only staff who have one.

`CASCADE` on both `document_id` and `staff_id`, and here that is the *safer* reading rather than
the dangerous one: deleting a document should take its grants, and an ex-employee's access should
not outlive their record. Contrast `0008`'s `staff.user_id`, which is `SET NULL` because it points
from a tenant row at a **global** one — cascading there would delete an employment record because
someone deleted their login. `granted_by` points at global `users` and is therefore `SET NULL` for
that same reason.

The index leads with `account_id` (SPEC-002 Step 3). Unlike `0007`, there is no lookup that needs
otherwise: every query here already knows its account.

Revision ID: 0009_document_access
Revises: 0008_staff_user_id
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0009_document_access"
down_revision: Union[str, None] = "0008_staff_user_id"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "document_access",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("account_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("document_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("staff_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("granted_by", postgresql.UUID(as_uuid=True), nullable=True),
        # Naive `DateTime`, matching `TimestampMixin` — **not** `timezone=True`. The first draft
        # used timezone-aware columns (copying `0007_telegram_links`, whose `linked_at` is its own
        # column rather than the mixin's) and `test_baseline_matches_metadata` caught the
        # mismatch immediately: the autogenerate oracle reported `modify_type` on both columns.
        # Worth the note, because the drift would have been invisible at runtime and only shown up
        # as a puzzling diff in whichever later migration was autogenerated next.
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["staff_id"], ["staff.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["granted_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "document_id", "staff_id", name="uq_document_access_doc_staff"
        ),
    )
    op.create_index(
        op.f("ix_document_access_account_id"), "document_access", ["account_id"], unique=False
    )

    # RLS **and** the drift guard for the table this migration creates — `0002_rls` and
    # `0001_pg_baseline` are each scoped to the tables present at their own point in the chain,
    # so the migration that creates a tenant table owns both its policy (SPEC-002 A8) and its
    # guard triggers. `0007_telegram_links` established this.
    #
    # `document_id` and `staff_id` are both guarded links: the trigger refuses a row whose
    # `account_id` disagrees with its document's or its staff member's, which is what stops a
    # grant from pointing across the tenant boundary. `granted_by` is not guarded, because
    # `users` is GLOBAL and has no `account_id` to disagree with.
    if op.get_bind().dialect.name == "postgresql":
        from mihomes.models import Base
        from mihomes.tenancy.drift_guard import trigger_ddl_statements
        from mihomes.tenancy.rls import policy_statements

        for stmt in policy_statements("document_access"):
            op.execute(stmt)
        for stmt in trigger_ddl_statements(Base.metadata, only_tables={"document_access"}):
            op.execute(stmt)


def downgrade() -> None:
    op.drop_index(op.f("ix_document_access_account_id"), table_name="document_access")
    op.drop_table("document_access")
