"""reconcile_schema_drift_h1_m11_m13_m15

Revision ID: 7514b34eed7b
Revises: 424437e5c0ef
Create Date: 2026-07-29 16:31:14.559693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7514b34eed7b'
down_revision: Union[str, None] = '424437e5c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- G-R4b: orphan cleanup MUST run before any FK creation ---------------
    # db.py forces `PRAGMA foreign_keys=ON` on every connection (including
    # Alembic's), and that pragma cannot be toggled inside the migration's
    # open transaction. Alembic batch-mode recreates each table and copies its
    # rows into a new table that already carries the new FK, so any row whose
    # FK value points at a missing parent would raise IntegrityError during the
    # copy. Every one of these six H1 FK columns (plus the two Transaction
    # links) is nullable, so we null-out dangling references — matching the
    # `ondelete='SET NULL'` intent and never deleting a row. (alerts.property_id
    # is a brand-new column, all NULL, so it needs no cleanup.)
    op.execute(
        "UPDATE appointments SET recurring_expense_id = NULL "
        "WHERE recurring_expense_id IS NOT NULL "
        "AND recurring_expense_id NOT IN (SELECT id FROM recurring_expenses)"
    )
    op.execute(
        "UPDATE issues SET reported_by_id = NULL "
        "WHERE reported_by_id IS NOT NULL "
        "AND reported_by_id NOT IN (SELECT id FROM staff)"
    )
    op.execute(
        "UPDATE issues SET resolved_by_id = NULL "
        "WHERE resolved_by_id IS NOT NULL "
        "AND resolved_by_id NOT IN (SELECT id FROM staff)"
    )
    op.execute(
        "UPDATE spaces SET zone_id = NULL "
        "WHERE zone_id IS NOT NULL "
        "AND zone_id NOT IN (SELECT id FROM zones)"
    )
    op.execute(
        "UPDATE tasks SET zone_id = NULL "
        "WHERE zone_id IS NOT NULL "
        "AND zone_id NOT IN (SELECT id FROM zones)"
    )
    op.execute(
        "UPDATE transactions SET appointment_id = NULL "
        "WHERE appointment_id IS NOT NULL "
        "AND appointment_id NOT IN (SELECT id FROM appointments)"
    )
    op.execute(
        "UPDATE transactions SET work_order_id = NULL "
        "WHERE work_order_id IS NOT NULL "
        "AND work_order_id NOT IN (SELECT id FROM work_orders)"
    )
    op.execute(
        "UPDATE work_orders SET issue_id = NULL "
        "WHERE issue_id IS NOT NULL "
        "AND issue_id NOT IN (SELECT id FROM issues)"
    )

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_property_id'), ['property_id'], unique=False)
        batch_op.create_foreign_key('fk_alerts_property_id_properties', 'properties', ['property_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_appointments_recurring_expense_id'), ['recurring_expense_id'], unique=False)
        batch_op.create_foreign_key('fk_appointments_recurring_expense_id_recurring_expenses', 'recurring_expenses', ['recurring_expense_id'], ['id'])

    with op.batch_alter_table('asset_price_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_property_id'), ['property_id'], unique=False)
        batch_op.create_unique_constraint('uq_budget_property_category_period', ['property_id', 'category', 'period', 'period_start'])

    with op.batch_alter_table('consumable_price_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_consumables_slug'), ['slug'], unique=True)

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_event_guest', ['event_id', 'guest_id'])

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_reported_by_id'), ['reported_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_resolved_by_id'), ['resolved_by_id'], unique=False)
        batch_op.create_foreign_key('fk_issues_resolved_by_id_staff', 'staff', ['resolved_by_id'], ['id'])
        batch_op.create_foreign_key('fk_issues_reported_by_id_staff', 'staff', ['reported_by_id'], ['id'])

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_entity_type'))
        batch_op.create_index('ix_note_entity', ['entity_type', 'entity_id'], unique=False)

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'CUSTOM_WEEKS', 'CUSTOM_MONTHS', name='expensefrequency'),
               existing_nullable=False)

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spaces_zone_id'), ['zone_id'], unique=False)
        batch_op.create_foreign_key('fk_spaces_zone_id_zones', 'zones', ['zone_id'], ['id'])

    with op.batch_alter_table('staff_pto_requests', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('tag_assignments', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_tag_assignment', ['tag_id', 'entity_type', 'entity_id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PLUMBING', 'HVAC', 'ELECTRICAL', 'FUEL_GAS', 'FIRE_SAFETY', 'SECURITY', 'HEALTH_ENV', 'EXTERIOR', 'LANDSCAPING', 'INTERIOR', 'APPLIANCES', 'OPERATIONS', 'STRATEGIC', 'GENERAL', name='taskcategory'),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_tasks_zone_id'), ['zone_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_zone_id_zones', 'zones', ['zone_id'], ['id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_appointment_id'), ['appointment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_vendor_id'), ['vendor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_work_order_id'), ['work_order_id'], unique=False)
        batch_op.create_foreign_key('fk_transactions_appointment_id_appointments', 'appointments', ['appointment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_transactions_work_order_id_work_orders', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.alter_column('due_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_work_orders_issue_id'), ['issue_id'], unique=False)
        batch_op.create_foreign_key('fk_work_orders_issue_id_issues', 'issues', ['issue_id'], ['id'])

    # --- M0/Q10: normalize enum server-defaults + existing rows to NAMES -----
    # None of these models use `values_callable`, so SQLAlchemy's Enum persists
    # the member *name* (UPPERCASE). But these columns were created with
    # lowercase `.value` server-defaults ('pending'/'good'/'ok'), so any row
    # inserted by the DB default is unreadable by the ORM (LookupError). Rewrite
    # both the stored data and the column default to the canonical NAME form.
    op.execute("UPDATE staff_pto_requests SET status = UPPER(status) WHERE status = LOWER(status)")
    op.execute("UPDATE books SET condition = UPPER(condition) WHERE condition = LOWER(condition)")
    op.execute("UPDATE consumables SET status = UPPER(status) WHERE status = LOWER(status)")

    # --- H6 (R4.5): re-run the daily-recurrence correction with the correct
    # enum casing. task_schedules.frequency is Enum(RecurrenceFrequency) with no
    # values_callable, so it persists member NAMES ('WEEKLY'/'DAILY'), not the
    # lowercase values. Migration e5f6a7b8c9d0 matched `frequency = 'weekly'`
    # (lowercase) and therefore updated zero rows. Redo it against 'WEEKLY'.
    op.execute("""
        UPDATE task_schedules
        SET frequency = 'DAILY'
        WHERE task_id IN (SELECT id FROM tasks WHERE title LIKE 'Daily:%')
        AND frequency = 'WEEKLY'
    """)
    with op.batch_alter_table('staff_pto_requests', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=8),
               server_default='PENDING', existing_nullable=False)
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('condition', existing_type=sa.String(length=9),
               server_default='GOOD', existing_nullable=False)
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=7),
               server_default='OK', existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Reverse M0/Q10 enum-default normalization (restore lowercase `.value`
    # defaults + data as they were before this migration).
    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=7),
               server_default='ok', existing_nullable=False)
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('condition', existing_type=sa.String(length=9),
               server_default='good', existing_nullable=False)
    with op.batch_alter_table('staff_pto_requests', schema=None) as batch_op:
        batch_op.alter_column('status', existing_type=sa.String(length=8),
               server_default='pending', existing_nullable=False)
    op.execute("UPDATE consumables SET status = LOWER(status) WHERE status = UPPER(status)")
    op.execute("UPDATE books SET condition = LOWER(condition) WHERE condition = UPPER(condition)")
    op.execute("UPDATE staff_pto_requests SET status = LOWER(status) WHERE status = UPPER(status)")

    # Reverse H6 (R4.5): restore Daily:% schedules to their pre-migration state.
    op.execute("""
        UPDATE task_schedules
        SET frequency = 'WEEKLY'
        WHERE task_id IN (SELECT id FROM tasks WHERE title LIKE 'Daily:%')
        AND frequency = 'DAILY'
    """)

    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_work_orders_issue_id_issues', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_work_orders_issue_id'))
        batch_op.alter_column('due_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_work_order_id_work_orders', type_='foreignkey')
        batch_op.drop_constraint('fk_transactions_appointment_id_appointments', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transactions_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_property_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_appointment_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_zone_id_zones', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_zone_id'))
        batch_op.alter_column('category',
               existing_type=sa.Enum('PLUMBING', 'HVAC', 'ELECTRICAL', 'FUEL_GAS', 'FIRE_SAFETY', 'SECURITY', 'HEALTH_ENV', 'EXTERIOR', 'LANDSCAPING', 'INTERIOR', 'APPLIANCES', 'OPERATIONS', 'STRATEGIC', 'GENERAL', name='taskcategory'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('tag_assignments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tag_assignment', type_='unique')

    with op.batch_alter_table('staff_pto_requests', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spaces_zone_id_zones', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_spaces_zone_id'))

    with op.batch_alter_table('recurring_expenses', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.Enum('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', 'CUSTOM_WEEKS', 'CUSTOM_MONTHS', name='expensefrequency'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_note_entity')
        batch_op.create_index(batch_op.f('ix_notes_entity_type'), ['entity_type'], unique=False)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_constraint('fk_issues_reported_by_id_staff', type_='foreignkey')
        batch_op.drop_constraint('fk_issues_resolved_by_id_staff', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_issues_resolved_by_id'))
        batch_op.drop_index(batch_op.f('ix_issues_reported_by_id'))

    with op.batch_alter_table('event_guests', schema=None) as batch_op:
        batch_op.drop_constraint('uq_event_guest', type_='unique')

    with op.batch_alter_table('consumables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consumables_slug'))
        batch_op.alter_column('slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('consumable_price_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budget_property_category_period', type_='unique')
        batch_op.drop_index(batch_op.f('ix_budgets_property_id'))

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('asset_price_entries', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_recurring_expense_id_recurring_expenses', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_appointments_recurring_expense_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_alerts_property_id_properties', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_property_id'))
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
