"""L9: make vendor cost/communication scores nullable

Revision ID: 4db594964c82
Revises: b3f5c1d9a72e
Create Date: 2026-07-29 21:36:10.657116

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4db594964c82'
down_revision: Union[str, None] = 'b3f5c1d9a72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_ratings', schema=None) as batch_op:
        batch_op.alter_column('cost_score',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('communication_score',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_ratings', schema=None) as batch_op:
        batch_op.alter_column('communication_score',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost_score',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
