"""add vendor_properties association M14

Revision ID: ce1a992f291e
Revises: 7514b34eed7b
Create Date: 2026-07-29 16:50:52.063955

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce1a992f291e'
down_revision: Union[str, None] = '7514b34eed7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_properties',
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('vendor_id', 'property_id')
    )

    # M14 data migration: unnest each vendor's JSON `property_ids` list into the
    # association table before dropping the column. json_each expands the array;
    # the INNER JOIN to properties drops any dangling IDs (the new PK's FKs would
    # otherwise be violated). DISTINCT guards against duplicate IDs in the blob.
    op.execute("""
        INSERT OR IGNORE INTO vendor_properties (vendor_id, property_id)
        SELECT DISTINCT v.id, CAST(je.value AS INTEGER)
        FROM vendors v
        JOIN json_each(v.property_ids) je
        JOIN properties p ON p.id = CAST(je.value AS INTEGER)
        WHERE v.property_ids IS NOT NULL
    """)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_column('property_ids')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_ids', sqlite.JSON(), nullable=True))

    # Re-materialize the JSON blob from the association rows (json_group_array
    # builds a JSON array of the linked property IDs per vendor).
    op.execute("""
        UPDATE vendors
        SET property_ids = (
            SELECT json_group_array(vp.property_id)
            FROM vendor_properties vp
            WHERE vp.vendor_id = vendors.id
        )
        WHERE EXISTS (
            SELECT 1 FROM vendor_properties vp WHERE vp.vendor_id = vendors.id
        )
    """)

    op.drop_table('vendor_properties')
    # ### end Alembic commands ###
