"""add_zones

Revision ID: e6b97b5b4e22
Revises: e5f6a7b8c9d0
Create Date: 2026-04-09 13:33:51.362410

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6b97b5b4e22'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_slug'), 'zones', ['slug'], unique=True)
    op.add_column('spaces', sa.Column('zone_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('zone_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Reverse exactly what upgrade() added: the two nullable zone_id columns and
    # the zones table. The original autogenerated downgrade was broken (H5): it
    # dropped a foreign key this migration never created, dropped tasks.zone_id
    # twice, and flipped an unrelated staff_pto_requests.updated_at to NOT NULL.
    # Batch mode is required for SQLite column drops.
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('zone_id')
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_column('zone_id')
    op.drop_index(op.f('ix_zones_slug'), table_name='zones')
    op.drop_table('zones')
